
spring:
 datasource:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:orcl
      username: xiaomablogweb
      password: xiaoma
jpa:
  hibernate:
     ddl-auto: update
     show-sql: true
server:
  port: 8090
 